### ISSUE TITLE
脚本已失效，更换32位bullshit无用

### ISSUE THREAD

**Issue by 1939323749** [MerlynAllen/JLU-VPN#2]

**Comment by MerlynAllen** [comment]
本脚本已经失效（近半年）。仅具有参考意义。欢迎移步 [MerlynAllen/jlu-vpns-dokodemo-door](https://github.com/MerlynAllen/jlu-vpns-dokodemo-door)。域名加密使用`aes-128-cfb`，key和iv均为`jluvpnisthegood!`。具体实现请见[这里](https://github.com/MerlynAllen/jlu-vpns-dokodemo-door/blob/main/jump.js)。
